#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mpmath
Version  : 1.0.0
Release  : 2
URL      : https://files.pythonhosted.org/packages/7a/05/b3d1472885d8dc0606936ea5da0ccb1b4785682e78ab15e34ada24aea8d5/mpmath-1.0.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/7a/05/b3d1472885d8dc0606936ea5da0ccb1b4785682e78ab15e34ada24aea8d5/mpmath-1.0.0.tar.gz
Summary  : Python library for arbitrary-precision floating-point arithmetic
Group    : Development/Tools
License  : BSD-3-Clause
Requires: mpmath-python3
Requires: mpmath-license
Requires: mpmath-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python3-dev
BuildRequires : setuptools

%description
No detailed description available

%package license
Summary: license components for the mpmath package.
Group: Default

%description license
license components for the mpmath package.


%package python
Summary: python components for the mpmath package.
Group: Default
Requires: mpmath-python3

%description python
python components for the mpmath package.


%package python3
Summary: python3 components for the mpmath package.
Group: Default
Requires: python3-core

%description python3
python3 components for the mpmath package.


%prep
%setup -q -n mpmath-1.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1530993166
find -name "*pyx" | xargs touch ||:
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/mpmath
cp LICENSE %{buildroot}/usr/share/doc/mpmath/LICENSE
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(-,root,root,-)
/usr/share/doc/mpmath/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
