#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mpmath
Version  : 1.1.0
Release  : 17
URL      : https://files.pythonhosted.org/packages/ca/63/3384ebb3b51af9610086b23ea976e6d27d6d97bf140a76a365bd77a3eb32/mpmath-1.1.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/ca/63/3384ebb3b51af9610086b23ea976e6d27d6d97bf140a76a365bd77a3eb32/mpmath-1.1.0.tar.gz
Summary  : Python library for arbitrary-precision floating-point arithmetic
Group    : Development/Tools
License  : BSD-3-Clause
Requires: mpmath-license = %{version}-%{release}
Requires: mpmath-python = %{version}-%{release}
Requires: mpmath-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
No detailed description available

%package license
Summary: license components for the mpmath package.
Group: Default

%description license
license components for the mpmath package.


%package python
Summary: python components for the mpmath package.
Group: Default
Requires: mpmath-python3 = %{version}-%{release}

%description python
python components for the mpmath package.


%package python3
Summary: python3 components for the mpmath package.
Group: Default
Requires: python3-core
Provides: pypi(mpmath)

%description python3
python3 components for the mpmath package.


%prep
%setup -q -n mpmath-1.1.0
cd %{_builddir}/mpmath-1.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1603396471
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/mpmath
cp %{_builddir}/mpmath-1.1.0/LICENSE %{buildroot}/usr/share/package-licenses/mpmath/01ee18d99c3880ba79a5032ebb9ba7ef9cd1f1cf
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mpmath/01ee18d99c3880ba79a5032ebb9ba7ef9cd1f1cf

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
